[[redirects]]
  from = "/api-hotline/*"
  to = "https://hotline.finance/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify Edge" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200